config/routes.rb
Rails.application.routes.draw do
  get 'pictures/index'

  get 'pictures/new'

  get 'pictures/create'

  get 'pictures/edit'

  get 'pictures/update'

  get 'pictures/destroy'

   root 'listings#index'
  resources :listings do
    resources :features
    resources :pictures
  end
 

end

app/models/feature.rb
class Feature < ActiveRecord::Base
	validates :description, presence: true 
	belongs_to :listing
end

app/models/listing.rb
class Listing < ActiveRecord::Base
	validates :title, presence: true
	has_many :features, dependent: :destroy
	has_many :pictures, dependent: :destroy

end

app/models/picture.rb
class Picture < ActiveRecord::Base
	validates :filename, presence: true 
	belongs_to :listing
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  def index
  	listingId = params[:listing_id]
  	@listing = Listing.find(listingId)
  	@features = @listing.features
  end

  def new 
  end

  def create
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def features_params
  params.require(:feature).permit(:listing_id, :description)
end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
  	@listings = Listing.all
  end

  def new
  	@listing = Listing.new
  end

  def create
  	@listing = Listing.new(listing_params)
  	if @listing.save
  		redirect_to root_path
  	else 
  		render "new"
  	end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def show
  end

  private 
  def listing_params
  	params.required(:listing).permit(:title, :description, :price)
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    @listing = Listing.find(params[:listing_id])
    @pictures = @listing.pictures
  end

  def new
    @listing = Listing.find(params[:listing_id])
    @picture = Picture.new(:listing => @listing)

  end

  def create
    listingId = params[:listing_id]
    @listing = Listing.find(listingId)
    @picture = Picture.new (picture_params)
    @picture.listing = @listing
    uploadIO = params[:pictures][:image]

    if uploadIO != nil
      t = Time.now
      ext = File.extname(uploadedIO.original_filename)
      tmmpFilename = "file_#{t.strftime("%Y%m%h%M")}" + ext
      @picture.filename = tmpFilename
      filename = Rails.root.join('public','images', tmpFilename)
      File.open(filename, 'wb') do |file|
        file.write(uploadIO.read)

  end
  if @picture.save
  redirect_to listing_pictures_path
else
    render 'new'
end
end
end

  def edit
    @listing = Listing.find(params[:listing_id])
    @picture = @listing.pictures.find(params[:id])
  end

  def update
  end

  def destroy
  end

 private
 def pictures_params
    params.require(:picture).permit(:listing_id, :title)
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/features_helper.rb
module FeaturesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/features/index.html.erb
<h1 class='page-heading'>All Features
<small><%=@listing.title%></small>
</h1>

<div class="row">
	<div class="col-md-12">
	<%= link_to 'New', new_listing_feature_path ,{class: 'btn btn-primary btn-md'}%>
	</div>
</div>
	<div class="row"> 
		<div class="col-md-12">
			<% if @features.length == 0 %>
			<p class="lead">No Features Found</p>
			<% else %>
<table class="table table-bordered table-striped table-responsive">
	<thead>
		<tr>
			<td>Description</td>
			<td></td>
			<td></td>
		</tr>
	</thead>
	<tbody>
		<% @features.each do |feature| %>	
		<tr>
			<td><%= feature.description %> </td>
			<td><%= link_to 'Edit', edit_listing_feature_path(@listing,feature) %> </td>
			<td><%= link_to 'Delete', [@listing,feature], method:delete, data:{confirm: 'Are you sure'} %></td>
		</tr>
		<% end %>
	</tbody>
</table>
			<% end %>
			</div>
	</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

<meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
 <title>Listings</title>
 <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
 <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse navbar-fixed-top">
     <div class="container">
       <div class="navbar-header">
         <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
           <span class="sr-only">Toggle navigation</span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
           <span class="icon-bar"></span>
         </button>
         <a class="navbar-brand" href="#">Project name</a>
       </div>
       <div id="navbar" class="collapse navbar-collapse">
         <ul class="nav navbar-nav">
           <li class="active"><a href="#">Home</a></li>
           <li><a href="#about">About</a></li>
           <li><a href="#contact">Contact</a></li>
         </ul>
       </div><!--/.nav-collapse -->
     </div>
   </nav>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/listings/_form.html.erb
<%= form_for @listing, :html => {class: "form-horizontal"} do |f| %>
<% if @listing.errors.any? %>
<div class='form-group'>
<div id='error_explanation'>
<h3><%= pluralize(@listing.errors.count, "error") %>
	prohibited this listing from being saved.</h3>
</div>
</div>	
<% end %>
<div class='form-group'>
	<div class='control-label col-md-2'>
		<%= f.label :title %>
	</div>
	<div class='col-md-3'>
		<%= f.text_field :title, {:class => 'form-control input-md', :maxlength => '140'} %>
	</div>
</div>

<div class='form-group'>
	<div class='control-label col-md-2'>
		<%= f.label :description %>
	</div>
	<div class='col-md-5'>
		<%= f.text_field :description, {:class => 'form-control input-md', :maxlength => '255'} %>
	</div>
</div>

<div class='form-group'>
	<div class='control-label col-md-2'>
		<%= f.label :price %>
	</div>
	<div class='col-md-2'>
		<%= f.text_field :price, {:class => 'form-control input-md', :maxlength => '16'} %>
	</div>
</div>

<div class='form-group'>
	<div class='col-md-12 text-center'> 
	<%= f.submit "Save", class: 'btn btn-primary btn-md' %> 
</div>
</div>

  <footer class="footer">
      <div class="container">
        <p class="text-muted">House Rental @ Copyright 2016</p>
      </div>
    </footer>
<% end %>

app/views/listings/index.html.erb
<h1 class="page-heading">All Listings</h1>
<div class="row">
	<div class="col-md-12">
	<%= link_to 'New', new_listing_path, {class: 'btn btn-primary btn-md'}%>
	</div>
</div>
	<div class="row"> 
		<div class="col-md-12">
			<% if @listings.length == 0 %>
			<p class="lead">No Listings Found</p>
			<% else %>
<table class="table table-bordered table-striped table-responsive">
	<thead>
		<tr>
			<tr>Title</tr>
			<td>Description</td>
			<td>Price</td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	</thead>
	<tbody>
		<% @listings.each do |listing| %>	
		<tr>
			<td><%= listing.title %> </td>
			<td><%= listing.description %> </td>
			<td><%= listing.price %> </td>
			<td><%= link_to 'Pictures', listing_pictures_path(listing) %> </td>
			<td><%= link_to 'Features', listing_features_path(listing) %> </td>
			<td><%= link_to 'Edit', edit_listing_path(listing) %> </td>
			<td><%= link_to 'Delete', listing, method: :delete, data:{confirm: 'Are you sure'} %></td>
			
		</tr>
		<% end %>
	</tbody>
</table>
			<% end %>
			</div>
	</div>

app/views/listings/new.html.erb
<h1>New Listing</h1>
<%= render 'form' %>

app/views/pictures/_form.html.erb
<%= form_for @listing, @picture, :html => {:multipart => true, :class => 'form-horizontal'} do |f| %>
<% if @picture.errors.any? %>
<div class='form-group'>
<div id='error_explanation'>
<h3><%= pluralize(@picture.errors.count, "error") %>
	prohibited this picture from being saved.</h3>
</div>
</div>	
<% end %>
<div class = "form-group"> 
	<div class = "control-label col-md-2"><% f.label :title %></div>
	<div class = "col-md-4"><% f.text_field :title, {:class => 'form-control input-md', :maxlength => '140'} %></div>
</div>
<div class = "form-group"> 
	<div class = "control-label col-md-2"><label>Select file</label></div>
	<div class = "col-md-4"><% f.file_field; {:class => 'form-control input-md'} %> </div>
</div>
<div class='form-group'>
	<div class='col-md-12 text-center'><%= f.submit "Save", class: 'btn btn-primary btn-md' %> </div>
</div>

<% end %>

app/views/pictures/create.html.erb
<h1>Pictures#create</h1>
<p>Find me in app/views/pictures/create.html.erb</p>

app/views/pictures/destroy.html.erb
<h1>Pictures#destroy</h1>
<p>Find me in app/views/pictures/destroy.html.erb</p>

app/views/pictures/edit.html.erb
<h1>Pictures#edit</h1>
<p>Find me in app/views/pictures/edit.html.erb</p>

app/views/pictures/index.html.erb
<h1 class='page-heading'>All Pictures
<small><%=@listing.title%></small>
</h1>
<div class="row">
	<div class="col-md-12">
	<%= link_to 'New', new_listing_picture_path ,{class: 'btn btn-primary btn-md'}%>
	</div>
</div>
	<div class="row"> 
		<div class="col-md-12">
			<% if @pictures.length == 0 %>
			<p class="lead">No Pictures Found</p>
			<% else %>
<table class="table table-bordered table-striped table-responsive">
	<thead>
		<tr>
			<td>Title</td>
			<td></td>
			<td></td>
		</tr>
	</thead>
	<tbody>
		<% @pictures.each do |picture| %>	
		<tr>
			<td><%= picture.title %> </td>
			<td><%= link_to 'Edit', edit_listing_picture_path(@listing,picture) %> </td>
			<td><%= link_to 'Delete', [@listing,picture], method:delete, data:{confirm: 'Are you sure'} %></td>
		</tr>
		<% end %>
	</tbody>
</table>
			<% end %>
			</div>
	</div>

app/views/pictures/new.html.erb
<h1>New Picture</h1>
<%= render 'form' %>

app/views/pictures/update.html.erb
<h1>Pictures#update</h1>
<p>Find me in app/views/pictures/update.html.erb</p>